In [48]:
import pandas as pd

In [49]:
df = pd.read_csv('../data/crypto_data.csv')

df.head()

,date,symbol,open,high,low,close,volume usdt,tradecount,token,hour,weekday
0,2020-12-25 05:00:00,1INCHUSDT,0.2000,3.0885,0.2000,2.5826,35530516,48768,1INCH,5,Friday
1,2020-12-25 06:00:00,1INCHUSDT,2.5824,2.6900,2.2249,2.5059,22440875,31099,1INCH,6,Friday
2,2020-12-25 07:00:00,1INCHUSDT,2.5152,2.8870,2.3609,2.6237,21300426,33001,1INCH,7,Friday
3,2020-12-25 08:00:00,1INCHUSDT,2.6318,2.8247,2.4650,2.6134,17491813,30459,1INCH,8,Friday
4,2020-12-25 09:00:00,1INCHUSDT,2.6104,2.7498,2.5629,2.6365,9919400,21023,1INCH,9,Friday

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1120061 entries, 0 to 1120060
Data columns (total 11 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   date         1120061 non-null  object
 1   symbol       1120061 non-null  object
 2   open         1120061 non-null  float64
 3   high         1120061 non-null  float64
 4   low          1120061 non-null  float64
 5   close        1120061 non-null  float64
 6   volume usdt  1120061 non-null  int64
 7   tradecount   1120061 non-null  int64
 8   token        1120061 non-null  object
 9   hour         1120061 non-null  int64
 10  weekday      1120061 non-null  object
dtypes: float64(4), int64(3), object(4)
memory usage: 94.0+ MB

Data has 1.12 million samples

In [51]:
df['date'] = pd.to_datetime(df['date'])
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day

In [52]:
df.head(10)

,date,symbol,open,high,low,close,volume usdt,tradecount,token,hour,weekday,year,month,day
0,2020-12-25 05:00:00,1INCHUSDT,0.2000,3.0885,0.2000,2.5826,35530516,48768,1INCH,5,Friday,2020,12,25
1,2020-12-25 06:00:00,1INCHUSDT,2.5824,2.6900,2.2249,2.5059,22440875,31099,1INCH,6,Friday,2020,12,25
2,2020-12-25 07:00:00,1INCHUSDT,2.5152,2.8870,2.3609,2.6237,21300426,33001,1INCH,7,Friday,2020,12,25
3,2020-12-25 08:00:00,1INCHUSDT,2.6318,2.8247,2.4650,2.6134,17491813,30459,1INCH,8,Friday,2020,12,25
4,2020-12-25 09:00:00,1INCHUSDT,2.6104,2.7498,2.5629,2.6365,9919400,21023,1INCH,9,Friday,2020,12,25
5,2020-12-25 10:00:00,1INCHUSDT,2.6365,2.9762,2.6345,2.7667,22372442,40186,1INCH,10,Friday,2020,12,25
6,2020-12-25 11:00:00,1INCHUSDT,2.7666,2.8740,2.5400,2.6476,16041844,32256,1INCH,11,Friday,2020,12,25
7,2020-12-25 12:00:00,1INCHUSDT,2.6500,2.8000,2.3719,2.4054,13354514,34153,1INCH,12,Friday,2020,12,25
8,2020-12-25 13:00:00,1INCHUSDT,2.4064,2.5003,2.2401,2.3100,16039128,42913,1INCH,13,Friday,2020,12,25
9,2020-12-25 14:00:00,1INCHUSDT,2.3100,2.3200,1.9000,2.0521,22430635,55081,1INCH,14,Friday,2020,12,25

In [53]:
c = df.columns
df['time_idx'] = df.groupby('symbol').cumcount()
df = df.reindex(columns=['time_idx', *c])
df.drop(columns=['date'], inplace=True)

In [54]:
df.head()

,time_idx,symbol,open,high,low,close,volume usdt,tradecount,token,hour,weekday,year,month,day
0,0,1INCHUSDT,0.2000,3.0885,0.2000,2.5826,35530516,48768,1INCH,5,Friday,2020,12,25
1,1,1INCHUSDT,2.5824,2.6900,2.2249,2.5059,22440875,31099,1INCH,6,Friday,2020,12,25
2,2,1INCHUSDT,2.5152,2.8870,2.3609,2.6237,21300426,33001,1INCH,7,Friday,2020,12,25
3,3,1INCHUSDT,2.6318,2.8247,2.4650,2.6134,17491813,30459,1INCH,8,Friday,2020,12,25
4,4,1INCHUSDT,2.6104,2.7498,2.5629,2.6365,9919400,21023,1INCH,9,Friday,2020,12,25

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1120061 entries, 0 to 1120060
Data columns (total 14 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   time_idx     1120061 non-null  int64
 1   symbol       1120061 non-null  object
 2   open         1120061 non-null  float64
 3   high         1120061 non-null  float64
 4   low          1120061 non-null  float64
 5   close        1120061 non-null  float64
 6   volume usdt  1120061 non-null  int64
 7   tradecount   1120061 non-null  int64
 8   token        1120061 non-null  object
 9   hour         1120061 non-null  int64
 10  weekday      1120061 non-null  object
 11  year         1120061 non-null  int32
 12  month        1120061 non-null  int32
 13  day          1120061 non-null  int32
dtypes: float64(4), int32(3), int64(4), object(3)
memory usage: 106.8+ MB

In [56]:
df.to_csv('../data/crypto_processed.csv', index=False)