## Merge all the individual tokens into one preprocessing-ready dataset
All of our tokens are tradable on Alpaca and we have historical data spanning back years to present day.  
* 18 tokens total - btc & eth = 16 tradable tokens

In [263]:
import pandas as pd
import glob
import os

In [264]:
# Directory containing the CSV files
tokens_dir = "../data/archive/tokens_historical"

# Get all CSV files in the directory
csv_files = glob.glob(os.path.join(tokens_dir, "*.csv"))

print(f"Found {len(csv_files)} CSV files")

# List to store individual dataframes
dfs = []

# Loop through each CSV file
for file in csv_files:
    print(f"Processing: {os.path.basename(file)}")

    # Read CSV, skipping the first row (metadata: url) and using the second row as header
    df_temp = pd.read_csv(file, skiprows=1)
    dfs.append(df_temp)

# Concatenate all dataframes
combined_df = pd.concat(dfs, ignore_index=True)

print(f"\nCombined dataframe shape: {combined_df.shape}")

Found 18 CSV files
Processing: CEX_ETHUSD_1h.csv
Processing: CEX_LTCUSD_1h.csv
Processing: CEX_AAVEUSD_1h.csv
Processing: CEX_DOTUSD_1h.csv
Processing: CEX_DOGEUSD_1h.csv
Processing: CEX_BCHUSD_1h.csv
Processing: CEX_UNIUSD_1h.csv
Processing: CEX_BATUSD_1h.csv
Processing: CEX_YFIUSD_1h.csv
Processing: CEX_SOLUSD_1h.csv
Processing: CEX_SUSHIUSD_1h.csv
Processing: CEX_SHIBUSD_1h.csv
Processing: CEX_XTZUSD_1h.csv
Processing: CEX_CRVUSD_1h.csv
Processing: CEX_GRTUSD_1h.csv
Processing: CEX_BTCUSD_1h.csv
Processing: CEX_AVAXUSD_1h.csv
Processing: CEX_LINKUSD_1h.csv

Combined dataframe shape: (434312, 26)

In [265]:
len(combined_df['symbol'].unique())

18

In [266]:
combined_df.columns

Index(['unix', 'date', 'symbol', 'open', 'high', 'low', 'close', 'Volume ETH',
       'Volume USD', 'Volume LTC', 'Volume AAVE', 'Volume DOT', 'Volume DOGE',
       'Volume BCH', 'Volume UNI', 'Volume BAT', 'Volume YFI', 'Volume SOL',
       'Volume SUSHI', 'Volume SHIB', 'Volume XTZ', 'Volume CRV', 'Volume GRT',
       'Volume BTC', 'Volume AVAX', 'Volume LINK'],
      dtype='object')

In [267]:
# Drop all Volume columns except Volume USD
volume_cols_to_drop = [col for col in combined_df.columns if 'Volume' in col and col != 'Volume USD']
combined_df = combined_df.drop(columns=volume_cols_to_drop)

print(f"Dropped {len(volume_cols_to_drop)} volume columns")
print(f"Remaining columns: {combined_df.columns.tolist()}")
combined_df.info()

Dropped 18 volume columns
Remaining columns: ['unix', 'date', 'symbol', 'open', 'high', 'low', 'close', 'Volume USD']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 434312 entries, 0 to 434311
Data columns (total 8 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   unix        434312 non-null  int64
 1   date        434312 non-null  object
 2   symbol      434312 non-null  object
 3   open        434312 non-null  float64
 4   high        434312 non-null  float64
 5   low         434312 non-null  float64
 6   close       434312 non-null  float64
 7   Volume USD  434312 non-null  float64
dtypes: float64(5), int64(1), object(2)
memory usage: 26.5+ MB

In [268]:
combined_df.sort_values(by=['symbol', 'unix'], ascending= True, inplace= True)

In [269]:
combined_df.head()

,unix,date,symbol,open,high,low,close,Volume USD
127819,1618999200,2021-04-21 10:00:00,AAVE/USD,362.63,362.63,360.00,360.00,1820.418840
127818,1619002800,2021-04-21 11:00:00,AAVE/USD,400.00,450.00,350.00,350.00,2221.133600
127817,1619006400,2021-04-21 12:00:00,AAVE/USD,360.00,399.00,360.00,399.00,653.863245
127816,1619010000,2021-04-21 13:00:00,AAVE/USD,389.99,400.00,380.00,400.00,2478.738400
127815,1619013600,2021-04-21 14:00:00,AAVE/USD,399.99,399.99,360.35,360.62,24450.482448

In [270]:
print(f"Date column type: {combined_df['date'].dtype}")
combined_df.info()

Date column type: object
<class 'pandas.core.frame.DataFrame'>
Index: 434312 entries, 127819 to 245793
Data columns (total 8 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   unix        434312 non-null  int64
 1   date        434312 non-null  object
 2   symbol      434312 non-null  object
 3   open        434312 non-null  float64
 4   high        434312 non-null  float64
 5   low         434312 non-null  float64
 6   close       434312 non-null  float64
 7   Volume USD  434312 non-null  float64
dtypes: float64(5), int64(1), object(2)
memory usage: 29.8+ MB

In [271]:
combined_df.groupby('symbol').count().sort_values('unix', ascending=False)

            unix   date   open   high    low  close  Volume USD
symbol
BTC/USD    77557  77557  77557  77557  77557  77557       77557
ETH/USD    70377  70377  70377  70377  70377  70377       70377
LTC/USD    45811  45811  45811  45811  45811  45811       45811
BCH/USD    44266  44266  44266  44266  44266  44266       44266
LINK/USD   24294  24294  24294  24294  24294  24294       24294
UNI/USD    21649  21649  21649  21649  21649  21649       21649
DOT/USD    20298  20298  20298  20298  20298  20298       20298
XTZ/USD    20010  20010  20010  20010  20010  20010       20010
SOL/USD    18748  18748  18748  18748  18748  18748       18748
DOGE/USD   17464  17464  17464  17464  17464  17464       17464
BAT/USD    14296  14296  14296  14296  14296  14296       14296
SHIB/USD   14256  14256  14256  14256  14256  14256       14256
CRV/USD    12686  12686  12686  12686  12686  12686       12686
AAVE/USD   11632  11632  11632  11632  11632  11632       11632
YFI/USD     9253   9253   9253   9253   9253   9253        9253
AVAX/USD    6005   6005   6005   6005   6005   6005        6005
SUSHI/USD   3402   3402   3402   3402   3402   3402        3402
GRT/USD     2308   2308   2308   2308   2308   2308        2308

In [272]:
new_df = pd.read_csv('../data/archive/bulk_older_data.csv')

In [273]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 434312 entries, 127819 to 245793
Data columns (total 8 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   unix        434312 non-null  int64
 1   date        434312 non-null  object
 2   symbol      434312 non-null  object
 3   open        434312 non-null  float64
 4   high        434312 non-null  float64
 5   low         434312 non-null  float64
 6   close       434312 non-null  float64
 7   Volume USD  434312 non-null  float64
dtypes: float64(5), int64(1), object(2)
memory usage: 29.8+ MB

In [274]:
combined_df.head()

,unix,date,symbol,open,high,low,close,Volume USD
127819,1618999200,2021-04-21 10:00:00,AAVE/USD,362.63,362.63,360.00,360.00,1820.418840
127818,1619002800,2021-04-21 11:00:00,AAVE/USD,400.00,450.00,350.00,350.00,2221.133600
127817,1619006400,2021-04-21 12:00:00,AAVE/USD,360.00,399.00,360.00,399.00,653.863245
127816,1619010000,2021-04-21 13:00:00,AAVE/USD,389.99,400.00,380.00,400.00,2478.738400
127815,1619013600,2021-04-21 14:00:00,AAVE/USD,399.99,399.99,360.35,360.62,24450.482448

In [275]:
# Prep the data fields
new_df.rename({'token': 'symbol', 'volume': 'Volume USD'}, axis=1, inplace=True)

new_df['date'] = pd.to_datetime(new_df['date'])
new_df['unix'] = new_df['date'].astype('int64') // 10**9
new_df['symbol'] = new_df['symbol'] + '/USD'

combined_df.drop(columns=['date'], inplace=True)
new_df.drop(columns=['date'], inplace=True)

In [276]:
# Add a merge key
combined_df['uid'] = combined_df['symbol'].str.strip() + combined_df['unix'].astype(str)
new_df['uid'] = new_df['symbol'].str.strip() + new_df['unix'].astype(str)

In [277]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1120061 entries, 0 to 1120060
Data columns (total 8 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   open        1120061 non-null  float64
 1   high        1120061 non-null  float64
 2   low         1120061 non-null  float64
 3   close       1120061 non-null  float64
 4   Volume USD  1120061 non-null  int64
 5   symbol      1120061 non-null  object
 6   unix        1120061 non-null  int64
 7   uid         1120061 non-null  object
dtypes: float64(4), int64(2), object(2)
memory usage: 68.4+ MB

In [278]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 434312 entries, 127819 to 245793
Data columns (total 8 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   unix        434312 non-null  int64
 1   symbol      434312 non-null  object
 2   open        434312 non-null  float64
 3   high        434312 non-null  float64
 4   low         434312 non-null  float64
 5   close       434312 non-null  float64
 6   Volume USD  434312 non-null  float64
 7   uid         434312 non-null  object
dtypes: float64(5), int64(1), object(2)
memory usage: 29.8+ MB

In [279]:
# Keep only rows from new_df that aren't in combined_df
new_data_only = new_df[~new_df['uid'].isin(combined_df['uid'])]

# Concatenate them
final_df = pd.concat([combined_df, new_data_only], ignore_index=True)
final_df.head(5)

,unix,symbol,open,high,low,close,Volume USD,uid
0,1618999200,AAVE/USD,362.63,362.63,360.00,360.00,1820.418840,AAVE/USD1618999200
1,1619002800,AAVE/USD,400.00,450.00,350.00,350.00,2221.133600,AAVE/USD1619002800
2,1619006400,AAVE/USD,360.00,399.00,360.00,399.00,653.863245,AAVE/USD1619006400
3,1619010000,AAVE/USD,389.99,400.00,380.00,400.00,2478.738400,AAVE/USD1619010000
4,1619013600,AAVE/USD,399.99,399.99,360.35,360.62,24450.482448,AAVE/USD1619013600

In [280]:
final_df.shape

(1253155, 8)

In [281]:
final_df['symbol'].value_counts()

symbol
BTC/USD      77948
ETH/USD      70943
LTC/USD      55375
BCH/USD      54985
BNB/USD      52032
ADA/USD      48198
ETC/USD      46942
TRX/USD      46905
LINK/USD     45492
DOGE/USD     41719
XMR/USD      40316
MATIC/USD    39243
ATOM/USD     39182
ALGO/USD     37900
DENT/USD     36320
RVN/USD      35616
HBAR/USD     35528
SOL/USD      32805
DOT/USD      30256
UNI/USD      29212
COMP/USD     29059
MKR/USD      28382
CRV/USD      28366
AVAX/USD     28271
BAL/USD      27934
SUSHI/USD    27510
AAVE/USD     26506
FIL/USD      26363
1INCH/USD    24672
SHIB/USD     23432
ICP/USD      21399
XTZ/USD      20010
DYDX/USD     18477
BAT/USD      14296
YFI/USD       9253
GRT/USD       2308
Name: count, dtype: int64

In [282]:
# Filter to keep only tokens with 30k+ samples for deep model
token_counts = final_df['symbol'].value_counts()
tokens_to_keep = token_counts[token_counts >= 30000].index.tolist()

tft_df = final_df[final_df['symbol'].isin(tokens_to_keep)].copy()

In [283]:
# Old training data has 1.2M samples
tft_df.shape

(867705, 8)

In [284]:
len(tft_df['symbol'].unique())

19

In [285]:
# Add the date column back
tft_df['date'] = pd.to_datetime(final_df['unix'], unit='s')

In [286]:
tft_df = tft_df[
  ['uid', 'unix', 'date', 'symbol', 'open', 'high', 'low', 'close', 'Volume USD']
]
tft_df.rename({'Volume USD': 'volume usd'}, inplace=True)
tft_df.sort_values(by='uid', inplace=True, ignore_index= True)

In [287]:
tft_df.head()

,uid,unix,date,symbol,open,high,low,close,Volume USD
0,ADA/USD1523937600,1523937600,2018-04-17 04:00:00,ADA/USD,0.25551,0.28800,0.25551,0.26664,2165077.0
1,ADA/USD1523941200,1523941200,2018-04-17 05:00:00,ADA/USD,0.26660,0.27798,0.26010,0.26200,2235633.0
2,ADA/USD1523944800,1523944800,2018-04-17 06:00:00,ADA/USD,0.26221,0.26396,0.24800,0.25664,2153964.0
3,ADA/USD1523948400,1523948400,2018-04-17 07:00:00,ADA/USD,0.25662,0.26300,0.25489,0.25698,1215621.0
4,ADA/USD1523952000,1523952000,2018-04-17 08:00:00,ADA/USD,0.25636,0.25998,0.25229,0.25631,896096.0

In [288]:
# Calculate time difference between consecutive rows for each token
tft_df['time_diff'] = tft_df.groupby('symbol')['unix'].diff()

# Find gaps (not 3600 seconds = 1 hour)
gaps = tft_df[tft_df['time_diff'] != 3600].copy()
gaps = gaps[gaps['time_diff'].notna()]  # Remove first row of each symbol (NaN diff)

# Calculate gap size in hours
gaps['gap_hours'] = gaps['time_diff'] / 3600

print(f"Total gaps found: {len(gaps)}")
print(f"\nGaps by token:")
print(gaps.groupby('symbol').size().sort_values(ascending=False))
print(f"\n\nLargest gaps (showing where and how large):")
gaps = gaps[['symbol', 'unix', 'date', 'time_diff', 'gap_hours']].sort_values(by='gap_hours', ascending=False, ignore_index=True)
gaps.head(10)

Total gaps found: 10735

Gaps by token:
symbol
ETH/USD      2718
BCH/USD      1972
BTC/USD      1670
SOL/USD      1111
LTC/USD      1075
DOT/USD       758
LINK/USD      659
DOGE/USD      611
ADA/USD        24
MATIC/USD      20
ATOM/USD       20
ALGO/USD       19
HBAR/USD       18
DENT/USD       18
RVN/USD        18
BNB/USD        16
TRX/USD         8
dtype: int64


Largest gaps (showing where and how large):

     symbol        unix                date  time_diff  gap_hours
0   DOT/USD  1743519600 2025-04-01 15:00:00  2822400.0      784.0
1   DOT/USD  1736262000 2025-01-07 15:00:00  2462400.0      684.0
2   BCH/USD  1736276400 2025-01-07 19:00:00  2347200.0      652.0
3  DOGE/USD  1746774000 2025-05-09 07:00:00  2307600.0      641.0
4  LINK/USD  1736305200 2025-01-08 03:00:00  2296800.0      638.0
5   DOT/USD  1727794800 2024-10-01 15:00:00  2142000.0      595.0
6   SOL/USD  1721250000 2024-07-17 21:00:00  2062800.0      573.0
7  LINK/USD  1743609600 2025-04-02 16:00:00  1980000.0      550.0
8  DOGE/USD  1726761600 2024-09-19 16:00:00  1965600.0      546.0
9  DOGE/USD  1740466800 2025-02-25 07:00:00  1922400.0      534.0

In [289]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1120061 entries, 0 to 1120060
Data columns (total 8 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   open        1120061 non-null  float64
 1   high        1120061 non-null  float64
 2   low         1120061 non-null  float64
 3   close       1120061 non-null  float64
 4   Volume USD  1120061 non-null  int64
 5   symbol      1120061 non-null  object
 6   unix        1120061 non-null  int64
 7   uid         1120061 non-null  object
dtypes: float64(4), int64(2), object(2)
memory usage: 68.4+ MB

### We have too many time gaps in the combined dataset so we will need to use the bulk data

In [290]:
new_df['date'] = pd.to_datetime(new_df['unix'], unit='s')
new_df = new_df[
  ['uid', 'unix', 'date', 'symbol', 'open', 'high', 'low', 'close', 'Volume USD']
]
new_df.rename({'Volume USD': 'volume_usd'}, axis=1, inplace=True)

In [291]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1120061 entries, 0 to 1120060
Data columns (total 9 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   uid         1120061 non-null  object
 1   unix        1120061 non-null  int64
 2   date        1120061 non-null  datetime64[ns]
 3   symbol      1120061 non-null  object
 4   open        1120061 non-null  float64
 5   high        1120061 non-null  float64
 6   low         1120061 non-null  float64
 7   close       1120061 non-null  float64
 8   volume_usd  1120061 non-null  int64
dtypes: datetime64[ns](1), float64(4), int64(2), object(2)
memory usage: 76.9+ MB

In [292]:
token_counts = new_df['symbol'].value_counts()
tokens_to_keep = token_counts[token_counts >= 27900].index.tolist()

tft_df = new_df[new_df['symbol'].isin(tokens_to_keep)].copy()
# tft_df.drop('time_diff', axis=1, inplace=True)
tft_df.sort_values(by='uid', inplace=True, ignore_index= True)

In [293]:
len(tft_df.symbol.unique())

21

In [294]:
tft_df.shape

(844335, 9)

In [295]:
tft_df.symbol.value_counts()

symbol
ETH/USD      54116
BTC/USD      54116
BNB/USD      52032
LTC/USD      51285
ADA/USD      48198
ETC/USD      46942
TRX/USD      46905
LINK/USD     41665
XMR/USD      40316
MATIC/USD    39243
ATOM/USD     39182
ALGO/USD     37900
DOGE/USD     37576
DENT/USD     36320
RVN/USD      35616
HBAR/USD     35528
BCH/USD      34086
COMP/USD     29059
MKR/USD      28382
BAL/USD      27934
SOL/USD      27934
Name: count, dtype: int64

In [296]:
tft_df.drop(columns=['uid'], inplace=True)

In [297]:
tft_df.to_csv('../data/coins.csv', index=False)